# All major configurations for this project
[runtime]
    # Select 
    # mode = "train" for training
    #      = "live" for live emo detector
    #      = "q2" for plots in q2
    mode = "train"

[dir]
    figures = "figs"
    data = "data"
    output = "outputs"

[img_info]
    size = [48, 48]
    num_classes = 7

[cnn]
    epoch = 60
    batch_size = 32
    learning_rate = 0.0001
    loss = "categorical_crossentropy"
    metrics = ["accuracy"]
    # checkpoint file name
    chk_path = "cp.ckpt"
    csv_log = "training.log"