# All major configurations for this project
[runtime]
    # Select 
    # mode = "FER-train" for training
    #      = "FER-predict" and show emoji
    #      = "q2" for plots and AUC in q2
    #      = "mt-q2" for data explore of machine tranlation dataset in q2
    #      = "plot_model_history" to plot the model history from logs
    #      = "mt-train" for english to kannada translation model
    mode = "mt-q2"

[dir]
    figures = "figs"
    data = "data"
    output = "outputs"
    FER-model = "fer-detector-model"

[img_info]
    size = [48, 48]
    num_classes = 7

[cnn]
    epoch = 60
    batch_size = 32
    learning_rate = 0.0001
    loss = "categorical_crossentropy"
    metrics = ["accuracy"]
    # checkpoint file name
    chk_path = "cp.ckpt"
    csv_log = "training.log"

# Settings for machine translation task
[mt]
    dataset = "en-kn-large"
    max_sen_word_limit = 5
    max_sen_token_size = 7